// Curated popular Indian dining hubs for instant, zero-latency search & suggestions
export const POPULAR_FOOD_HUBS = [
  // Bengaluru
  {
    id: 'blr_indiranagar',
    name: 'Indiranagar',
    formattedAddress: '100ft Road & 12th Main, Indiranagar, Bengaluru',
    city: 'Bengaluru',
    lat: 12.9784,
    lon: 77.6408,
    type: 'Trending Food Hub',
  },
  {
    id: 'blr_koramangala',
    name: 'Koramangala',
    formattedAddress: '5th Block & 80ft Rd, Koramangala, Bengaluru',
    city: 'Bengaluru',
    lat: 12.9352,
    lon: 77.6245,
    type: 'Cafés & Breweries',
  },
  {
    id: 'blr_mgroad',
    name: 'MG Road & Church St',
    formattedAddress: 'Church Street & MG Road, Central Bengaluru',
    city: 'Bengaluru',
    lat: 12.9756,
    lon: 77.6066,
    type: 'Iconic Bistros',
  },
  {
    id: 'blr_whitefield',
    name: 'Whitefield',
    formattedAddress: 'ITPL Main Road, Whitefield, Bengaluru',
    city: 'Bengaluru',
    lat: 12.9698,
    lon: 77.7500,
    type: 'Gourmet Dining',
  },
  {
    id: 'blr_hsr',
    name: 'HSR Layout',
    formattedAddress: '27th Main, Sector 1 & 2, HSR Layout, Bengaluru',
    city: 'Bengaluru',
    lat: 12.9121,
    lon: 77.6446,
    type: 'Artisanal Eateries',
  },
  {
    id: 'blr_jpnagar',
    name: 'JP Nagar',
    formattedAddress: '24th Main, 5th Phase, JP Nagar, Bengaluru',
    city: 'Bengaluru',
    lat: 12.9063,
    lon: 77.5857,
    type: 'Family Dining',
  },

  // Mumbai
  {
    id: 'bom_bandra',
    name: 'Bandra West',
    formattedAddress: 'Pali Hill & Hill Road, Bandra West, Mumbai',
    city: 'Mumbai',
    lat: 19.0596,
    lon: 72.8295,
    type: 'Trendy Dining & Cafes',
  },
  {
    id: 'bom_juhu',
    name: 'Juhu',
    formattedAddress: 'Juhu Tara Road & Beach, Mumbai',
    city: 'Mumbai',
    lat: 19.1075,
    lon: 72.8263,
    type: 'Coastal & Fine Dining',
  },
  {
    id: 'bom_colaba',
    name: 'Colaba',
    formattedAddress: 'Colaba Causeway, South Mumbai',
    city: 'Mumbai',
    lat: 18.9067,
    lon: 72.8147,
    type: 'Heritage Bistros',
  },
  {
    id: 'bom_powai',
    name: 'Powai',
    formattedAddress: 'Hiranandani Gardens, Powai, Mumbai',
    city: 'Mumbai',
    lat: 19.1176,
    lon: 72.9060,
    type: 'Lakeside Lounges',
  },

  // Delhi NCR
  {
    id: 'del_cp',
    name: 'Connaught Place',
    formattedAddress: 'Inner Circle & Radial Roads, CP, New Delhi',
    city: 'Delhi NCR',
    lat: 28.6315,
    lon: 77.2167,
    type: 'Iconic Central Delhi',
  },
  {
    id: 'del_hkv',
    name: 'Hauz Khas Village',
    formattedAddress: 'HKV & Deer Park, South Delhi',
    city: 'Delhi NCR',
    lat: 28.5494,
    lon: 77.2001,
    type: 'Boho & Rooftop Eateries',
  },
  {
    id: 'del_cybercity',
    name: 'Cyber Hub Gurugram',
    formattedAddress: 'DLF Cyber City, Phase 2, Gurugram, Delhi NCR',
    city: 'Delhi NCR',
    lat: 28.4952,
    lon: 77.0892,
    type: 'Premium Gastropubs',
  },
  {
    id: 'del_khanmarket',
    name: 'Khan Market',
    formattedAddress: 'Middle Lane, Khan Market, New Delhi',
    city: 'Delhi NCR',
    lat: 28.6003,
    lon: 77.2272,
    type: 'Upscale Cafés & Patisseries',
  },

  // Kolkata
  {
    id: 'ccu_parkst',
    name: 'Park Street',
    formattedAddress: 'Park Street Dining Strip, Central Kolkata',
    city: 'Kolkata',
    lat: 22.5510,
    lon: 88.3524,
    type: 'Colonial & Modern Dining',
  },
  {
    id: 'ccu_saltlake',
    name: 'Salt Lake Sector V',
    formattedAddress: 'Sector V & Bidhannagar, Kolkata',
    city: 'Kolkata',
    lat: 22.5804,
    lon: 88.4378,
    type: 'Craft Breweries & Buffets',
  },
  {
    id: 'ccu_ballygunge',
    name: 'Ballygunge',
    formattedAddress: 'Southern Avenue & Ballygunge, Kolkata',
    city: 'Kolkata',
    lat: 22.5280,
    lon: 88.3653,
    type: 'Fine Bengali & Continental',
  },

  // Hyderabad
  {
    id: 'hyd_jubilee',
    name: 'Jubilee Hills',
    formattedAddress: 'Road No. 36 & 45, Jubilee Hills, Hyderabad',
    city: 'Hyderabad',
    lat: 17.4319,
    lon: 78.4073,
    type: 'Luxury Dining & Lounges',
  },
  {
    id: 'hyd_banjara',
    name: 'Banjara Hills',
    formattedAddress: 'Road No. 12, Banjara Hills, Hyderabad',
    city: 'Hyderabad',
    lat: 17.4156,
    lon: 78.4350,
    type: 'Fine Dining & Hyderabadi',
  },
  {
    id: 'hyd_gachibowli',
    name: 'Gachibowli',
    formattedAddress: 'Financial District, Gachibowli, Hyderabad',
    city: 'Hyderabad',
    lat: 17.4401,
    lon: 78.3489,
    type: 'Tech Corridor Eateries',
  },
]
